version: "3.8"
services:
  solidity-frontend:
    image: 132830644905.dkr.ecr.us-east-2.amazonaws.com/solidityscan-frontend:$ENV
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "45947:3000"
    env_file:
      - .env
    command: >
      sh -c "yarn global add serve && serve -s build"
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 1m
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
