name: SolidityScan Frontend Image Build Workflow

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: "Build environment"
        required: true
        default: "stage"
        type: choice
        options:
          - stage
          - prod
          - backoffice-stage
          - backoffice-prod

jobs:
  build:
    env:
      ENV: ${{ inputs.ENV }}
      DOCKER_COMPOSE_PATH: /home/runner/work/solidity-scanner-frontend/solidity-scanner-frontend/docker-compose.yml
      PROJECT_DIRECTORY: /home/runner/work/solidity-scanner-frontend/solidity-scanner-frontend/

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setting aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Cloning files from S3
        run: |
          aws s3 cp s3://credshields-dev/env_file/frontend.env ${PROJECT_DIRECTORY}/.env
      - name: Logging in on aws ecr
        run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 132830644905.dkr.ecr.us-east-2.amazonaws.com

      - name: Build the Docker image
        run: |
          docker-compose -f ${DOCKER_COMPOSE_PATH} build
      - name: Pusing created images to ECR
        run: docker-compose -f ${DOCKER_COMPOSE_PATH} push
