# This is a basic workflow that is manually triggered

name: SolidityScan Frontend Image Build Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    env:
      DOCKER_COMPOSE_PATH: /home/runner/work/solidity-scanner-frontend/docker-compose.yml
      PROJECT_DIRECTORY: /home/runner/work/solidity-scanner-frontend/solidity-scanner-frontend/

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setting aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Cloning files from S3
        run: |
          aws s3 cp s3://credshields-dev/env_file/frontend.env ${PROJECT_DIRECTORY}/.env

      - name: Logging in on aws ecr
        run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 132830644905.dkr.ecr.us-east-2.amazonaws.com

      - name: Build the Docker image
        run: |
          docker-compose -f ${DOCKER_COMPOSE_PATH} build

      - name: Pusing created images to ECR
        run: docker-compose -f ${DOCKER_COMPOSE_PATH} push
